### ISSUE TITLE
task changes

### ISSUE THREAD

**Issue by JDWammes** [JDWammes/fractals#4]
I think there are a few things we could change to make this simpler, and more in line with what others have done.

1. ISI needn't be variable, so this is superfluous code
2. We can do 100% valid trials (there is ALWAYS a target)
3. It can ALWAYS be the A image in the first n learning rounds, then B image in the transfer round
4. Image should remain on screen until target is found **(done)**
5. No break between learning and transfer, to the participant it should be seamless **(done)**

I've taken care of 4 and 5, but thought you, @moopet17, might want to try playing around with the rest. If not, I'm happy to do it. What you did works beautifully for the most part, so this should be a walk in the park since its just simplifying things. You can check some possible sample code I had written in old_functions_fractals.py if you get stuck.

**Comment by moopet17** [comment]
1. done. Deleted the gen_isi functions and added default value of 1 for isi in the function definition of vis_search
2. Ok, I did not have time to remove the code for this, but 100% is the default.
3. Done.
